In [1]:
import pandas as pd
from sqlalchemy import create_engine

In [2]:
file = "listingsutf.csv"
airbnb_df = pd.read_csv(file, error_bad_lines=False)
airbnb_df.head()

,id,listing_url,scrape_id,last_scraped,name,summary,space,description,experiences_offered,neighborhood_overview,...,instant_bookable,is_business_travel_ready,cancellation_policy,require_guest_profile_picture,require_guest_phone_verification,calculated_host_listings_count,calculated_host_listings_count_entire_homes,calculated_host_listings_count_private_rooms,calculated_host_listings_count_shared_rooms,reviews_per_month
0,2384,https://www.airbnb.com/rooms/2384,2.019050e+13,5/19/2019,Hyde Park - Walk to UChicago/Metra to McCormic...,"Be the sole guest in a quiet, vintage, 2nd flo...","The private bedroom has a queen size bed, ches...","Be the sole guest in a quiet, vintage, 2nd flo...",none,My apartment is located one block from beautif...,...,f,f,strict_14_with_grace_period,f,f,1.0,0.0,1.0,0.0,2.81
1,4505,https://www.airbnb.com/rooms/4505,2.019050e+13,5/19/2019,We're back. 365 Great Reviews. 1 bad one.,"We took the winter off, made things nicer arou...","We travel a lot, we know what people need. We...","We took the winter off, made things nicer arou...",none,NaN,...,t,f,moderate,f,f,1.0,1.0,0.0,0.0,2.96
2,7126,https://www.airbnb.com/rooms/7126,2.019050e+13,5/19/2019,Tiny Studio Apartment 94 Walk Score,A very small studio in a wonderful neighborhood.,This is a very small studio apartment with a ...,A very small studio in a wonderful neighborhoo...,none,"Ukrainian Village was just named ""Hottest Neig...",...,f,f,moderate,f,f,1.0,1.0,0.0,0.0,2.81
3,9811,https://www.airbnb.com/rooms/9811,2.019050e+13,5/19/2019,Barbara's Hideaway - Old Town,One-bedroom hideaway tucked into Old Town step...,"This lovely one bedroom ""hideaway"" is located ...",One-bedroom hideaway tucked into Old Town step...,none,Chicagoâ€™s Old Town neighborhood is squeezed ...,...,t,f,strict_14_with_grace_period,f,f,11.0,11.0,0.0,0.0,0.56
4,10610,https://www.airbnb.com/rooms/10610,2.019050e+13,5/19/2019,3 Comforts of Cooperative Living,The condo is the 2nd floor in a lovely 1912 3-...,Newly furnished with queen bed and the comfort...,The condo is the 2nd floor in a lovely 1912 3-...,none,It's a 10 minute walk from the lakefront bike ...,...,t,f,moderate,f,f,5.0,1.0,4.0,0.0,0.68

In [3]:
list(airbnb_df.columns.values)

['id',
 'listing_url',
 'scrape_id',
 'last_scraped',
 'name',
 'summary',
 'space',
 'description',
 'experiences_offered',
 'neighborhood_overview',
 'notes',
 'transit',
 'access',
 'interaction',
 'house_rules',
 'thumbnail_url',
 'medium_url',
 'picture_url',
 'xl_picture_url',
 'host_id',
 'host_url',
 'host_name',
 'host_since',
 'host_location',
 'host_about',
 'host_response_time',
 'host_response_rate',
 'host_acceptance_rate',
 'host_is_superhost',
 'host_thumbnail_url',
 'host_picture_url',
 'host_neighbourhood',
 'host_listings_count',
 'host_total_listings_count',
 'host_verifications',
 'host_has_profile_pic',
 'host_identity_verified',
 'street',
 'neighbourhood',
 'neighbourhood_cleansed',
 'neighbourhood_group_cleansed',
 'city',
 'state',
 'zipcode',
 'market',
 'smart_location',
 'country_code',
 'country',
 'latitude',
 'longitude',
 'is_location_exact',
 'property_type',
 'room_type',
 'accommodates',
 'bathrooms',
 'bedrooms',
 'beds',
 'bed_type',
 'amenities',
 'square_feet',
 'price',
 'weekly_price',
 'monthly_price',
 'security_deposit',
 'cleaning_fee',
 'guests_included',
 'extra_people',
 'minimum_nights',
 'maximum_nights',
 'minimum_minimum_nights',
 'maximum_minimum_nights',
 'minimum_maximum_nights',
 'maximum_maximum_nights',
 'minimum_nights_avg_ntm',
 'maximum_nights_avg_ntm',
 'calendar_updated',
 'has_availability',
 'availability_30',
 'availability_60',
 'availability_90',
 'availability_365',
 'calendar_last_scraped',
 'number_of_reviews',
 'number_of_reviews_ltm',
 'first_review',
 'last_review',
 'review_scores_rating',
 'review_scores_accuracy',
 'review_scores_cleanliness',
 'review_scores_checkin',
 'review_scores_communication',
 'review_scores_location',
 'review_scores_value',
 'requires_license',
 'license',
 'jurisdiction_names',
 'instant_bookable',
 'is_business_travel_ready',
 'cancellation_policy',
 'require_guest_profile_picture',
 'require_guest_phone_verification',
 'calculated_host_listings_count',
 'calculated_host_listings_count_entire_homes',
 'calculated_host_listings_count_private_rooms',
 'calculated_host_listings_count_shared_rooms',
 'reviews_per_month']

In [4]:
airbnb_df_new = airbnb_df[["neighbourhood","neighborhood_overview", "latitude", "longitude", "property_type","bathrooms", "room_type",
                           "accommodates", "bedrooms", "beds", "price", "number_of_reviews", "review_scores_rating"]].copy()

airbnb_df_new.head()

,neighbourhood,neighborhood_overview,latitude,longitude,property_type,bathrooms,room_type,accommodates,bedrooms,beds,price,number_of_reviews,review_scores_rating
0,Hyde Park,My apartment is located one block from beautif...,41.78886,-87.58671,Condominium,1.0,Private room,1.0,1.0,1.0,$50.00,149.0,100.0
1,Little Village,NaN,41.85495,-87.69696,Apartment,1.0,Entire home/apt,7.0,3.0,4.0,$117.00,368.0,96.0
2,Ukrainian Village,"Ukrainian Village was just named ""Hottest Neig...",41.90289,-87.68182,Apartment,1.0,Entire home/apt,2.0,1.0,1.0,$80.00,338.0,92.0
3,Old Town,Chicagoâ€™s Old Town neighborhood is squeezed ...,41.91769,-87.63788,Apartment,1.0,Entire home/apt,4.0,1.0,2.0,$150.00,35.0,92.0
4,Hyde Park,It's a 10 minute walk from the lakefront bike ...,41.79708,-87.59195,Apartment,1.0,Private room,2.0,1.0,1.0,$35.00,38.0,85.0

In [5]:
airbnb_df_sqrft = airbnb_df[["neighbourhood","neighborhood_overview", "latitude", "longitude", "property_type","bathrooms", "room_type",
                           "accommodates", "bedrooms", "beds","square_feet", "price", "number_of_reviews", "review_scores_rating"]].copy()
airbnb_df_sqrft.head()

,neighbourhood,neighborhood_overview,latitude,longitude,property_type,bathrooms,room_type,accommodates,bedrooms,beds,square_feet,price,number_of_reviews,review_scores_rating
0,Hyde Park,My apartment is located one block from beautif...,41.78886,-87.58671,Condominium,1.0,Private room,1.0,1.0,1.0,NaN,$50.00,149.0,100.0
1,Little Village,NaN,41.85495,-87.69696,Apartment,1.0,Entire home/apt,7.0,3.0,4.0,NaN,$117.00,368.0,96.0
2,Ukrainian Village,"Ukrainian Village was just named ""Hottest Neig...",41.90289,-87.68182,Apartment,1.0,Entire home/apt,2.0,1.0,1.0,NaN,$80.00,338.0,92.0
3,Old Town,Chicagoâ€™s Old Town neighborhood is squeezed ...,41.91769,-87.63788,Apartment,1.0,Entire home/apt,4.0,1.0,2.0,NaN,$150.00,35.0,92.0
4,Hyde Park,It's a 10 minute walk from the lakefront bike ...,41.79708,-87.59195,Apartment,1.0,Private room,2.0,1.0,1.0,NaN,$35.00,38.0,85.0

In [6]:
airbnb_df_sqrft = airbnb_df_sqrft.dropna()
airbnb_df_sqrft.head()

,neighbourhood,neighborhood_overview,latitude,longitude,property_type,bathrooms,room_type,accommodates,bedrooms,beds,square_feet,price,number_of_reviews,review_scores_rating
22,Uptown,Uptown is considered the most diverse neighbo...,41.96804,-87.65123,Apartment,1.0,Private room,1.0,1.0,1.0,1350.0,$48.00,142.0,98.0
25,North Center,Trendy Roscoe Village offers a variety of bout...,41.94364,-87.68155,Apartment,2.0,Entire home/apt,8.0,3.0,4.0,1300.0,$275.00,14.0,94.0
30,Ukrainian Village,NEIGHBORHOOD: This beautiful three story Victo...,41.89753,-87.67315,Apartment,1.0,Entire home/apt,3.0,2.0,2.0,1300.0,$75.00,58.0,96.0
49,West Loop/Greektown,"It is Chicago's hottest area, centrally locate...",41.88467,-87.64487,Condominium,1.5,Entire home/apt,3.0,2.0,2.0,1050.0,$195.00,62.0,98.0
53,West Loop/Greektown,To the West is the west loop and most of the n...,41.88623,-87.64040,Loft,2.0,Entire home/apt,6.0,3.0,3.0,1600.0,$175.00,10.0,82.0

In [7]:
airbnb_df_new = airbnb_df_new.rename(columns={"review_scores_rating": "rating"})
airbnb_df_new.head()

,neighbourhood,neighborhood_overview,latitude,longitude,property_type,bathrooms,room_type,accommodates,bedrooms,beds,price,number_of_reviews,rating
0,Hyde Park,My apartment is located one block from beautif...,41.78886,-87.58671,Condominium,1.0,Private room,1.0,1.0,1.0,$50.00,149.0,100.0
1,Little Village,NaN,41.85495,-87.69696,Apartment,1.0,Entire home/apt,7.0,3.0,4.0,$117.00,368.0,96.0
2,Ukrainian Village,"Ukrainian Village was just named ""Hottest Neig...",41.90289,-87.68182,Apartment,1.0,Entire home/apt,2.0,1.0,1.0,$80.00,338.0,92.0
3,Old Town,Chicagoâ€™s Old Town neighborhood is squeezed ...,41.91769,-87.63788,Apartment,1.0,Entire home/apt,4.0,1.0,2.0,$150.00,35.0,92.0
4,Hyde Park,It's a 10 minute walk from the lakefront bike ...,41.79708,-87.59195,Apartment,1.0,Private room,2.0,1.0,1.0,$35.00,38.0,85.0

In [8]:
airbnb_df_new["price"]= airbnb_df_new["price"].str.replace('$', '')
airbnb_df_new.head()

,neighbourhood,neighborhood_overview,latitude,longitude,property_type,bathrooms,room_type,accommodates,bedrooms,beds,price,number_of_reviews,rating
0,Hyde Park,My apartment is located one block from beautif...,41.78886,-87.58671,Condominium,1.0,Private room,1.0,1.0,1.0,50.00,149.0,100.0
1,Little Village,NaN,41.85495,-87.69696,Apartment,1.0,Entire home/apt,7.0,3.0,4.0,117.00,368.0,96.0
2,Ukrainian Village,"Ukrainian Village was just named ""Hottest Neig...",41.90289,-87.68182,Apartment,1.0,Entire home/apt,2.0,1.0,1.0,80.00,338.0,92.0
3,Old Town,Chicagoâ€™s Old Town neighborhood is squeezed ...,41.91769,-87.63788,Apartment,1.0,Entire home/apt,4.0,1.0,2.0,150.00,35.0,92.0
4,Hyde Park,It's a 10 minute walk from the lakefront bike ...,41.79708,-87.59195,Apartment,1.0,Private room,2.0,1.0,1.0,35.00,38.0,85.0

In [9]:
airbnb_df_sqrft["price"]= airbnb_df_sqrft["price"].str.replace('$', '')
airbnb_df_sqrft.head()

,neighbourhood,neighborhood_overview,latitude,longitude,property_type,bathrooms,room_type,accommodates,bedrooms,beds,square_feet,price,number_of_reviews,review_scores_rating
22,Uptown,Uptown is considered the most diverse neighbo...,41.96804,-87.65123,Apartment,1.0,Private room,1.0,1.0,1.0,1350.0,48.00,142.0,98.0
25,North Center,Trendy Roscoe Village offers a variety of bout...,41.94364,-87.68155,Apartment,2.0,Entire home/apt,8.0,3.0,4.0,1300.0,275.00,14.0,94.0
30,Ukrainian Village,NEIGHBORHOOD: This beautiful three story Victo...,41.89753,-87.67315,Apartment,1.0,Entire home/apt,3.0,2.0,2.0,1300.0,75.00,58.0,96.0
49,West Loop/Greektown,"It is Chicago's hottest area, centrally locate...",41.88467,-87.64487,Condominium,1.5,Entire home/apt,3.0,2.0,2.0,1050.0,195.00,62.0,98.0
53,West Loop/Greektown,To the West is the west loop and most of the n...,41.88623,-87.64040,Loft,2.0,Entire home/apt,6.0,3.0,3.0,1600.0,175.00,10.0,82.0

In [10]:
#rds_connection_string = "root:shayan1371@127.0.0.1/airbnb_db"
#engine = create_engine(f'mysql+pymysql://{rds_connection_string}')
engine = create_engine("sqlite:///airbnb.sqlite")

In [11]:
engine.table_names()

[]

In [12]:
airbnb_df_new.to_sql(name='airbnb', con=engine, if_exists='append', index = False)
airbnb_df_sqrft.to_sql(name='airbnb_sqrft', con=engine, if_exists='append', index = False)

In [14]:
pd.read_sql_query("SELECT latitude FROM airbnb", con = engine).head()

   latitude
0  41.78886
1  41.85495
2  41.90289
3  41.91769
4  41.79708